
#ifndef LS_CODE_H__
#define LS_CODE_H__


typedef enum
{
    LS_EVT_BASE = 0,

    LS_EVT_STATIC_DETECTED,
    LS_EVT_MOTION_DETECTED,




    LS_EVT_ALERT_LOW_POWER,
    LS_EVT_ALERT_OVERSPEED,
    LS_EVT_ALERT_GEO_FENCE_1,
    LS_EVT_ALERT_GEO_FENCE_2,
    LS_EVT_ALERT_GEO_FENCE_3,
    LS_EVT_ALERT_GEO_FENCE_4,
    LS_EVT_ALERT_MOVEMENT,


    LS_EVT_ALERT_PRE_MOTION,
    LS_EVT_ALERT_MOTION,

    LS_EVT_ALERT_PRE_STATIC, 
    LS_EVT_ALERT_STATIC,

    LS_EVT_ALERT_PRE_TILT,
    LS_EVT_ALERT_TILT,

    LS_EVT_ALERT_PRE_FALLDOWN,
    LS_EVT_ALERT_FALLDOWN,

    LS_EVT_ALERT_PRE_SOS,
    LS_EVT_ALERT_SOS,

    LS_EVT_SINGLE_LOCATOR,
    LS_EVT_CONTINUE_LOCATOR,

    LS_EVT_POWER_ON,
    LS_EVT_POWER_OFF,
    LS_EVT_POWER_LOW,
    LS_EVT_POWER_RESET,
    LS_EVT_POWER_FORCE_RESET,

    LS_EVT_BUTTON_PRESS,
    LS_EVT_ALARMCLOCK_ACT,
//    LS_EVT_ALARMCLOCK_DEACT,
//    LS_EVT_BUTTON_EVT,

    LS_EVT_CONF_RINGTONE,
    LS_EVT_CONF_MIC,
    LS_EVT_CONF_SPEAKER,
    LS_EVT_ALARM_CLOCK_START,

    LS_EVT_GSM_ECHO_TEST,
    LS_EVT_GSM_ECHO_STOP,

    LS_EVT_GPRS_DISCONNECT,

    LS_EVT_BLE_LOC, //BLE 定位
    LS_EVT_WIFI_LOC,             //
    LS_EVT_GSM_LOC, //GSM 基站定位
    LS_EVT_GPS_LOC, //GPS 定位


    LS_EVT_SMS_KBND,

    LS_EVT_UPDATE_HISTORICAL_DATA, //发送历史数据
    LS_EVT_UPDATE_ACTIVITY_DATA, //发送活跃度的数据
}ls_evt_accept_t;



/*
    LS_EVT_ALERT_LOW_POWER,
    LS_EVT_ALERT_OVERSPEED,
    LS_EVT_ALERT_GEO_FENCE_1,
    LS_EVT_ALERT_GEO_FENCE_2,
    LS_EVT_ALERT_GEO_FENCE_3,
    LS_EVT_ALERT_GEO_FENCE_4,
    LS_EVT_ALERT_MOVEMENT,
    LS_EVT_ALERT_MOTION,
    LS_EVT_ALERT_STATIC,
    LS_EVT_ALERT_TILT,
    LS_EVT_ALERT_PRE_FALLDOWN,
    LS_EVT_ALERT_FALLDOWN,
*/
typedef enum {
    ALERT_TYPE_NONE = 0,
    //Alert
    ALERT_TYPE_LOW_POWER   = 0X00000001,

    ALERT_TYPE_OVER_SPEED  = 0X00000002,
    ALERT_TYPE_GEO_1       = 0X00000004,
    ALERT_TYPE_GEO_2       = 0X00000008,
    ALERT_TYPE_GEO_3       = 0X00000010,
    ALERT_TYPE_GEO_4       = 0X00000020,
    ALERT_TYPE_MOVEMNT     = 0X00000040,

    ALERT_TYPE_MOTION      = 0X00000080,
    ALERT_TYPE_STATIC      = 0X00000100,
    ALERT_TYPE_TILT        = 0X00000200,
    ALERT_TYPE_FALLDOWN    = 0X00000400,

    ALERT_TYPE_SOS         = 0x80000000,
}AlertType_en;

#define ALERT_TYPE_ALERT_MARK  0X7FFFFFFF
#define ALERT_TYPE_SOS_MARK    0x80000000

typedef enum {
    ALERT_LOC_NONE = 0,
    ALERT_LOC_BLE,
    ALERT_LOC_GPS,
    ALERT_LOC_WIFI,
}AlertLoc_en;
#endif


